"""Django settings for atlasserver project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import platform
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / ".env", override=True)

SECRET_KEY = os.environ.get("ATLASSERVER_DJANGO_SECRET_KEY")

TEST_USERS = [int(x) for x in os.environ.get("ATLASSERVER_TEST_USERS", "").split(",") if x]

# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# macOS means a development machine, but that is not the only kind, and sometimes a Mac needs to
# simulate production: an explicit ATLASSERVER_DEBUG wins in both directions, and only when it is
# unset does the platform decide. Without the override, a developer on Linux picks up the
# production hardening below, where SECURE_SSL_REDIRECT makes runserver answer every request with
# a 301 to a port serving no TLS.
_debug_env = os.environ.get("ATLASSERVER_DEBUG", "").strip().lower()
DEBUG = _debug_env in {"1", "true", "yes"} if _debug_env else platform.system() == "Darwin"

# Not "*": django.contrib.sites is not installed, so the password reset email builds its link from
# the Host header. Accepting any host lets an attacker send a victim a reset link pointing at a
# server they control. Override with a comma-separated ATLASSERVER_ALLOWED_HOSTS if the server is
# reached under another name.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ATLASSERVER_ALLOWED_HOSTS",
        "fallingstar-data.com,.fallingstar-data.com,.qub.ac.uk,deckard,localhost,127.0.0.1,[::1]",
    ).split(",")
    if host.strip()
]

ADMINS = [
    ("Luke Shingles", "luke.shingles@gmail.com"),
]  # send server error notifications to this person
MANAGERS = ADMINS


INSTALLED_APPS = [
    "atlasserver.forcephot",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "geoip2",
]

MIDDLEWARE = [
    "django.middleware.common.BrokenLinkEmailsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

filecacheroot = Path("/files/atlasforced/django_cache")
if not filecacheroot.is_dir():
    filecacheroot = Path("/tmp/atlasforced/django_cache")


CACHES = {
    # file-based rather than locmem, because the DRF throttle counters live in the default cache
    # and each mod_wsgi process would otherwise keep its own, multiplying the effective rate limit
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": filecacheroot / "default",
    },
    "taskderived": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": filecacheroot / "taskderived",
        # generated plot data for finished tasks. It only changes when the result file does, so a
        # long timeout is fine, but not an unbounded one: entries for tasks that are never viewed
        # again would otherwise be kept forever, and any that were somehow stale could never heal
        "TIMEOUT": 60 * 60 * 24 * 30,  # 30 days
        "OPTIONS": {"MAX_ENTRIES": 5000},
    },
    "usagestats": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": filecacheroot / "usagestats",
    },
}

ROOT_URLCONF = "atlasserver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, Path(BASE_DIR, "atlasserver", "forcephot", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "atlasserver.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        "ENGINE": "django.db.backends.mysql",
        # 'OPTIONS': {
        #     # 'read_default_file': '/usr/local/etc/my.cnf',
        # },
        "NAME": os.environ.get("ATLASSERVER_DJANGO_MYSQL_DBNAME"),
        "USER": os.environ.get("ATLASSERVER_DJANGO_MYSQL_USER"),
        "PASSWORD": os.environ.get("ATLASSERVER_DJANGO_MYSQL_PASSWORD"),
        "HOST": "localhost",  # Or an IP Address that your DB is hosted on
        "PORT": "3306",
        # reuse connections instead of opening and closing one per request. The queue page polls
        # every couple of seconds per open tab, so the connection setup was a large share of the
        # work done for a typical request. Each mod_wsgi process holds one connection per worker
        # thread, so keep this shorter than the server's wait_timeout.
        "CONN_MAX_AGE": int(os.environ.get("ATLASSERVER_DB_CONN_MAX_AGE", "60")),
        # a pooled connection can have been closed by the server since it was last used; without
        # this the next request to pick it up fails instead of transparently reconnecting
        "CONN_HEALTH_CHECKS": True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-uk"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# keyed on DEBUG, not on the platform: a Linux development machine with ATLASSERVER_DEBUG=1 would
# otherwise get /forcedphot/static/ URLs that runserver does not serve — no CSS and no bundles —
# and a Mac simulating production (ATLASSERVER_DEBUG=0) needs the prefix the real deployment has
PATHPREFIX = "" if DEBUG else "/forcedphot"
STATIC_URL = f"{PATHPREFIX}/static/"

STATIC_ROOT = Path(BASE_DIR, "static")
RESULTS_DIR = Path(STATIC_ROOT, "results")

USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False

# If your Django app is behind a proxy that sets a header to specify secure
# connections, AND that proxy ensures that user-submitted headers with the
# same name are ignored (so that people can't spoof it), set this value to
# a tuple of (header_name, header_value). For any requests that come in with
# that header/value, request.is_secure() will return True.
# WARNING! Only set this if you fully understand what you're doing. Otherwise,
# you may be opening yourself up to a security risk.
# SECURE_PROXY_SSL_HEADER = ('X-FORWARDED-PROTO', 'https')
if not DEBUG:
    # httpconf.txt sets this header unconditionally (so a client cannot spoof it). The previous
    # value keyed off SERVER_SOFTWARE, which Apache always populates with its own banner, so
    # request.scheme was a constant that depended on the ServerTokens setting rather than on the
    # protocol the request actually arrived over.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    # the four warnings that `manage.py check --deploy` raised. Guarded, because development runs
    # over plain http on localhost and secure-only cookies would never be sent there.
    #
    # SECURE_SSL_REDIRECT never fires as things stand: httpconf.txt sets X-Forwarded-Proto to https
    # unconditionally, so request.is_secure() is always true. It is here as a backstop for a
    # deployment that stops setting that header, which would otherwise quietly serve plain http.
    # annotated rather than left to inference: without a declared type these are literal types, and
    # settings_test.py (which switches them back off, see the note there) would not type check
    SECURE_SSL_REDIRECT: bool = True
    SESSION_COOKIE_SECURE: bool = True
    CSRF_COOKIE_SECURE: bool = True
    # one year, and only for this host: subdomains are not all served by this deployment
    SECURE_HSTS_SECONDS: int = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS: bool = False
    SECURE_HSTS_PRELOAD: bool = False

CSRF_TRUSTED_ORIGINS = [
    "https://*.qub.ac.uk",
    "https://fallingstar-data.com",
    "http://localhost",
    "http://127.0.0.1",
    "http://deckard:8086",
]

# When set to True, if the request URL does not match any of the patterns in the URLconf and it doesn't end in a slash,
# an HTTP redirect is issued to the same URL with a slash appended. Note that the redirect may cause any data submitted
# in a POST request to be lost.
APPEND_SLASH = True

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "task-list"

LOGOUT_REDIRECT_URL = "index"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"],
    "DEFAULT_PAGINATION_CLASS": "atlasserver.forcephot.pagination.TaskPagination",
    "PAGE_SIZE": 6,
    "DEFAULT_THROTTLE_CLASSES": [
        # 'rest_framework.throttling.ScopedRateThrottle',
        "atlasserver.forcephot.throttles.ForcedPhotRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "forcephottasks": "60/min",
    },
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    # JSON first: DRF picks the first renderer for an "Accept: */*" request (what a script sends
    # when it sets no Accept header), and TemplateHTMLRenderer answers those with an HTML page,
    # reducing validation errors to a bare "400 Bad Request". Browsers ask for text/html
    # explicitly, so they still get the HTML pages.
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.TemplateHTMLRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "EXCEPTION_HANDLER": "atlasserver.forcephot.exception.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# the API was documented only by a hand-written page, which had to be kept in step with the
# serializer by hand. The generated schema is derived from the code, so it cannot drift.
SPECTACULAR_SETTINGS = {
    "TITLE": "ATLAS Forced Photometry API",
    "DESCRIPTION": (
        "Request forced photometry at any position on the sky over the full history of the ATLAS survey.\n\n"
        "Authenticate with a token from /api-token-auth/ and send it as `Authorization: Token <token>`.\n"
        "See the API guide at /apiguide/ for worked examples."
    ),
    "VERSION": "1.0.0",
    # the schema endpoint itself is not part of the API being described
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/",
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# admin error mail is sent synchronously from the request thread, so without a timeout an
# unreachable mail server holds that worker (and eventually the whole pool) indefinitely
EMAIL_TIMEOUT = 10

EMAIL_HOST_USER = os.environ.get("ATLASSERVER_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("ATLASSERVER_EMAIL_HOST_PASSWORD")
SERVER_EMAIL = os.environ.get("ATLASSERVER_EMAIL_HOST_USER")
DEFAULT_FROM_EMAIL = os.environ.get("ATLASSERVER_EMAIL_HOST_USER")

GEOIP_PATH = Path(__file__).parent


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "timestamp": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "atlasserver.forcephot.misc.AdminEmailHandlerNo404",
            "email_backend": EMAIL_BACKEND,
            "include_html": True,
        },
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "djangodebug.log",
            "formatter": "timestamp",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "mail_admins", "file"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
