# Generated by Django 3.1.2 on 2020-10-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0002_auto_20201004_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcephottask',
            old_name='user_id',
            new_name='user',
        ),
    ]
