# Generated by Django 3.1.2 on 2020-10-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0003_auto_20201004_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcephottask',
            old_name='user',
            new_name='user_id',
        ),
    ]
