# Generated by Django 3.1.2 on 2020-10-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0006_auto_20201004_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcephottask',
            old_name='userid',
            new_name='user',
        ),
    ]
