# Generated by Django 3.1.2 on 2020-10-05 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forcephot', '0007_auto_20201005_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForcePhotTask',
            new_name='Tasks',
        ),
    ]
