# Generated by Django 3.1.2 on 2020-10-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0009_auto_20201005_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='userid',
            new_name='user',
        ),
    ]
