# Generated by Django 3.1.2 on 2020-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0010_auto_20201005_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='use_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
