# Generated by Django 3.1.2 on 2020-10-09 12:47

import atlasserver.forcephot.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0012_auto_20201009_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dec',
            field=atlasserver.forcephot.models.RoundingDecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ra',
            field=atlasserver.forcephot.models.RoundingDecimalField(decimal_places=4, max_digits=8),
        ),
    ]
