# Generated by Django 3.1.2 on 2020-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0013_auto_20201009_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dec',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ra',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
