# Generated by Django 6.0 on 2026-01-09 13:33

import atlasserver.forcephot.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('starttimestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('finishtimestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('mpc_name', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Minor Planet Center object name (overrides RA/Dec)')),
                ('ra', models.FloatField(blank=True, default=None, null=True, verbose_name='Right Ascension (degrees)')),
                ('dec', models.FloatField(blank=True, default=None, null=True, verbose_name='Declination (degrees)')),
                ('mjd_min', models.FloatField(blank=True, default=atlasserver.forcephot.models.get_mjd_min_default, null=True, verbose_name='MJD min')),
                ('mjd_max', models.FloatField(blank=True, default=None, null=True, verbose_name='MJD max')),
                ('comment', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('use_reduced', models.BooleanField(default=False, verbose_name='Use reduced images instead of difference images')),
                ('send_email', models.BooleanField(default=True, verbose_name='Email me when completed')),
                ('from_api', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('error_msg', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Error messages during execution')),
                ('is_archived', models.BooleanField(default=False)),
                ('radec_epoch_year', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Epoch year')),
                ('propermotion_ra', models.FloatField(blank=True, null=True, verbose_name='Proper motion RA (mas/yr)')),
                ('propermotion_dec', models.FloatField(blank=True, null=True, verbose_name='Proper motion Dec (mas/yr)')),
                ('queuepos_relative', models.IntegerField(blank=True, default=None, null=True, verbose_name='Queue position')),
                ('request_type', models.CharField(choices=[('FP', 'Forced Photometry Data'), ('IMGZIP', 'Image Zip'), ('SSOSTACK', 'Solar System object image stack')], default='FP', max_length=8)),
                ('task_modified_datetime', models.DateTimeField(auto_now=True)),
                ('parent_task', models.ForeignKey(default=None, limit_choices_to={'request_type': 'FP'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagerequest', to='forcephot.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
