# Generated by Django 6.0 on 2026-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userqueuedtasks_on_submit',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='User queued tasks when submitted'),
        ),
    ]
