# Generated by Django 6.0.7 on 2026-07-31 12:30

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("forcephot", "0002_task_userqueuedtasks_on_submit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="callback_url",
            field=models.URLField(
                blank=True, default=None, max_length=500, null=True, verbose_name="Completion callback URL (API only)"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["is_archived", "user", "-timestamp", "-id"], name="task_userlist_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["finishtimestamp", "is_archived", "queuepos_relative"], name="task_queue_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent_task", "is_archived", "id"], name="task_imagereq_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["request_type", "finishtimestamp"], name="task_maint_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["timestamp"], name="task_timestamp_idx"),
        ),
    ]
