# Generated by Django 3.1.2 on 2020-10-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0005_auto_20201004_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcephottask',
            old_name='user',
            new_name='userid',
        ),
    ]
