# Generated by Django 6.1 on 2026-08-14 20:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("forcephot", "0008_mpc_name_not_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attempt_count",
            field=models.IntegerField(default=0, verbose_name="Execution attempts"),
        ),
    ]
