# Generated by Django 3.1.2 on 2020-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0011_tasks_use_reduced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='ra',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='use_reduced',
            field=models.BooleanField(default=False, verbose_name='Use reduced images instead of difference'),
        ),
    ]
