# Generated by Django 3.1.2 on 2020-10-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0016_auto_20201019_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dec',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ra',
            field=models.FloatField(blank=True),
        ),
    ]
