# Generated by Django 3.1.2 on 2020-10-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0018_auto_20201020_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dec',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='ra',
            field=models.FloatField(default=None),
        ),
    ]
