# Generated by Django 3.1.2 on 2020-10-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0020_auto_20201021_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForcePhotResult',
            new_name='Result',
        ),
    ]
