# Generated by Django 3.1.2 on 2020-10-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0022_auto_20201021_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='dec',
            new_name='declination',
        ),
    ]
