# Generated by Django 3.1.2 on 2020-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0023_auto_20201021_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='mjd_min',
            field=models.FloatField(blank=True, default=59122.0, null=True, verbose_name='MJD min'),
        ),
    ]
