---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-toml
          #- id: check-yaml
          - id: detect-private-key
          - id: destroyed-symlinks
          - id: fix-byte-order-marker
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: trailing-whitespace
            exclude_types: [svg]
    # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    #   rev: 0.2.3
    #   hooks:
    #       - id: yamlfmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.6
      hooks:
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.6
      hooks:
        - id: ruff-format
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.6.1
    #   hooks:
    #       - id: mypy
    #         language: system
    #         # additional_dependencies: [numpy, types-PyYAML, types-psutil, django-stubs, python-dotenv, django-filter, djangorestframework, djangorestframework-stubs,
    #         #     django-geoip2-extras, astrocalc, julian, pycountry, matplotlib]
    #         types: [python]
    #         args: [--ignore-missing-imports]
    #         require_serial: true
    # - repo: local
    #   hooks:
    #       - id: pylint
    #         name: pylint
    #         entry: pylint
    #         language: system
    #         types: [python]
    #         args: [-rn, -sn, --errors-only]
