[tool.black]
line-length = 120
preview = true
extend-exclude = "plot_atlas_fp.py"

[tool.flake8]
ignore = "N806"
max-line-length = 120
count = true
exclude = [
    '.git',
    '__pycache__',
    'docs/source/conf.py',
    'old',
    'build',
    'plot_atlas_fp.py'
]

[tool.pylint.format]
max-line-length = "120"

[tool.pylama]
max-line-length = 120

[tool.pycodestyle]
max-line-length = 120