import typing as t
from typing import override

from django.core.cache import caches

# the same tuple ForcePhotPermission branches on, so the two cannot drift on what counts as a read.
# Safe methods are throttled far more loosely than writes, but not exempt: the queue page polls the
# task list every few seconds, so reads are the traffic most likely to be hammered, and they were
# previously unlimited -- an unauthenticated caller could poll a task detail as fast as the server
# would answer.
from rest_framework.permissions import SAFE_METHODS
from rest_framework.request import Request
from rest_framework.throttling import SimpleRateThrottle

if t.TYPE_CHECKING:
    # only for the annotations. DRF resolves DEFAULT_THROTTLE_CLASSES while rest_framework.views is
    # still being imported, so importing APIView here at run time is a circular import that leaves
    # the whole app unable to start. rest_framework.permissions above is safe: views.py already
    # imports it at module scope.
    from rest_framework.views import APIView

# Scope used for safe methods, in place of whatever the view declares for writes. Separate so that
# a burst of reads cannot use up a user's ability to submit, and so the two can be tuned apart.
READ_SCOPE = "forcephotread"


class ForcedPhotRateThrottle(SimpleRateThrottle):
    """Limit the rate of API calls by different amounts for various parts of the API.

    Any view that has the `throttle_scope` property set will be throttled. The unique cache key is
    generated by concatenating the user id of the request with the scope being applied, so reads
    and writes are counted separately.
    """

    scope_attr = "throttle_scope"

    # not the default cache: see the "throttle" alias in settings for why these counters must not
    # share a directory with the queue-recalc flag and the PDF render locks
    cache = caches["throttle"]

    def __init__(self) -> None:
        # Override the usual SimpleRateThrottle, because we can't determine
        # the rate until called by the view.
        pass

    @override
    def allow_request(self, request: Request, view: "APIView") -> bool:
        # We can only determine the scope once we're called by the view.
        writescope = getattr(view, self.scope_attr, None)

        # If a view does not have a `throttle_scope` always allow the request
        if not writescope:
            return True

        self.scope = READ_SCOPE if request.method in SAFE_METHODS else writescope

        # Determine the allowed request rate as we normally would during
        # the `__init__` call.
        self.rate = self.get_rate()
        self.num_requests, self.duration = self.parse_rate(self.rate)

        # We can now proceed as normal.
        return super().allow_request(request, view)

    @override
    def get_cache_key(self, request: Request, view: "APIView") -> str:
        """If `view.throttle_scope` is not set, don't apply this throttle.

        Otherwise generate the unique cache key by concatenating the user id
        with the '.throttle_scope` property of the view.
        """
        ident = request.user.pk if request.user.is_authenticated else self.get_ident(request)

        return self.cache_format % {"scope": self.scope, "ident": ident}
