# Generated by Django 3.1.2 on 2020-10-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0004_auto_20201004_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcephottask',
            old_name='user_id',
            new_name='user',
        ),
    ]
