# Generated by Django 3.1.2 on 2020-10-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0008_auto_20201005_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='userid',
        ),
    ]
