# Generated by Django 3.1.2 on 2020-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0015_auto_20201014_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='ra',
            field=models.FloatField(),
        ),
    ]
