# Generated by Django 3.1.2 on 2020-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0017_auto_20201020_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dec',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ra',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
