# Generated by Django 3.1.2 on 2020-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0019_auto_20201020_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcePhotResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('mjd', models.FloatField()),
                ('m', models.FloatField()),
                ('dm', models.FloatField()),
                ('ujy', models.IntegerField()),
                ('dujy', models.IntegerField()),
                ('filter', models.CharField(max_length=1)),
                ('err', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('maj', models.FloatField()),
                ('min', models.FloatField()),
                ('phi', models.FloatField()),
                ('apfit', models.FloatField()),
                ('zp', models.FloatField()),
                ('obs', models.CharField(max_length=32)),
                ('use_reduced', models.BooleanField(default=False, verbose_name='Use reduced images instead of difference images')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='mjd_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='MJD max'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mjd_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='MJD min'),
        ),
        migrations.AlterField(
            model_name='task',
            name='use_reduced',
            field=models.BooleanField(default=False, verbose_name='Use reduced images instead of difference images'),
        ),
    ]
