# Generated by Django 3.1.2 on 2020-10-21 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0021_auto_20201021_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='chi_over_n',
            field=models.FloatField(default=-99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='sky',
            field=models.FloatField(default=-99),
            preserve_default=False,
        ),
    ]
