# Generated by Django 3.1.3 on 2020-11-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0024_auto_20201030_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='mjd_min',
            field=models.FloatField(blank=True, default=59125.0, null=True, verbose_name='MJD min'),
        ),
    ]
