# Generated by Django 3.1.3 on 2020-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0026_auto_20201102_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finishtimestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
