# Generated by Django 3.1.3 on 2020-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0027_task_finishtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
