# Generated by Django 3.1.2 on 2020-11-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0029_auto_20201123_0916'),
        ('forcephot', '0029_auto_20201120_1619'),
    ]

    operations = [
    ]
