# Generated by Django 3.1.4 on 2020-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0029_auto_20201123_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starttimestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
