# Generated by Django 3.1.2 on 2020-12-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0030_task_starttimestamp'),
        ('forcephot', '0030_merge_20201123_0941'),
    ]

    operations = [
    ]
