# Generated by Django 3.1.4 on 2020-12-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0031_merge_20201202_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
    ]
