# Generated by Django 3.1.7 on 2021-02-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0032_remove_task_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='finishtimestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='starttimestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
