# Generated by Django 3.1.7 on 2021-02-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0033_auto_20210221_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='archived',
            new_name='is_archived',
        ),
    ]
