# Generated by Django 3.1.7 on 2021-02-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0034_auto_20210221_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='from_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
