# Generated by Django 3.1.7 on 2021-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0035_auto_20210222_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
