# Generated by Django 3.1.7 on 2021-02-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0036_task_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='continent_code',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
