# Generated by Django 3.1.7 on 2021-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0037_auto_20210222_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='continent_code',
        ),
        migrations.AddField(
            model_name='task',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
