# Generated by Django 3.1.7 on 2021-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0041_task_mpc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_msg',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Errors during execution'),
        ),
    ]
