# Generated by Django 3.1.7 on 2021-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0042_task_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error_msg',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Error messages during execution'),
        ),
    ]
