# Generated by Django 3.1.7 on 2021-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcephot', '0043_auto_20210223_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dec',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ra',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
