---
name: Django CI

on:
    merge_group:
    push:
    pull_request:
    repository_dispatch:
        types: [trigger_checks]

env:
    ATLASSERVER_DJANGO_MYSQL_DBNAME: atlasserver
    ATLASSERVER_DJANGO_MYSQL_USER: root
    ATLASSERVER_DJANGO_MYSQL_PASSWORD: root
    ATLASSERVER_EMAIL_HOST_USER: atlasforced@gmail.com
    ATLASSERVER_DJANGO_SECRET_KEY: ${{secrets.ATLASSERVER_DJANGO_SECRET_KEY}}

jobs:
    build:
        environment: test
        runs-on: ubuntu-latest

        # services:
        #     mysql:
        #         image: mysql:5.7
        #         env:
        #             MYSQL_ALLOW_EMPTY_PASSWORD: yes
        #             MYSQL_DATABASE: atlasserver
        #             MYSQL_USER: root
        #             MYSQL_PASSWORD: password
        #             MYSQL_ROOT_PASSWORD: password
        #         ports:
        #             - 3306
        #         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python and uv
              uses: astral-sh/setup-uv@v7
              with:
                  activate-environment: true

            - name: Install atlasserver
              run: |
                  cat atlasserver/settings_test.txt >> atlasserver/settings.py
                  uv pip install -e .

            - name: Install geoip databases
              run: ./update_geoipdatabase.sh

            - name: Set up MySQL
              run: |
                  sudo /etc/init.d/mysql start
                  echo "mysql started"
                  mysql -e "CREATE DATABASE ${{env.ATLASSERVER_DJANGO_MYSQL_DBNAME}};" -u${{env.ATLASSERVER_DJANGO_MYSQL_USER}} -p${{env.ATLASSERVER_DJANGO_MYSQL_PASSWORD}}
                  ./manage.py makemigrations
                  ./manage.py migrate

            - name: Run Django Tests
              run: |
                  ./manage.py test

            - name: Start and stop server
              run: |
                  atlaswebserver start
                  atlastaskrunner start
                  atlastaskrunner stop
                  atlaswebserver stop
