name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd atlasserver
        ls
        echo "SECRET_KEY = '3gy2&d^d59mvspz^ey&+9fvf6sgpob8m2+g6@cp5=^h1!5c5l0'" > atlasserver/settings_secret.py
        pwd
        python3 manage.py shell -c "from django.core.management.utils import get_random_secret_key; print(f'SECRET_KEY = \'{get_random_secret_key()}\'')" > atlasserver/settings_secret_new.py
        mv atlasserver/settings_secret_new.py atlasserver/settings_secret.py
        cat atlasserver/settings_secret.py
        python3 manage.py test
