---
name: Linter

on:
    merge_group:
    push:
    pull_request:
    repository_dispatch:
        types: [trigger_checks]

jobs:
    lint:
        name: Lint (ruff, mypy, pylint)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Set up Python and uv
              uses: astral-sh/setup-uv@v7
              with:
                  activate-environment: true

            - name: Install atlasserver
              run: |
                  uv pip install -e .

            - name: Run Ruff
              if: always()
              run: |
                  uv run -- ruff --version
                  uv run -- ruff check --exit-non-zero-on-fix --no-fix

            - name: Run Ruff Format
              if: always()
              run: uv run -- ruff format --check --exit-non-zero-on-format

            - name: Run mypy
              run: |
                  uv run -- mypy --install-types --non-interactive

            - name: Run pylint
              run: |
                  uv run -- pylint atlasserver
