---
name: Linter

on:
    merge_group:
    push:
    pull_request:
    repository_dispatch:
        types: [trigger_checks]

jobs:
    lint:
        name: Lint (ruff, mypy, pylint)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip uv
                  uv pip install --system mypy
                  uv pip install --system -e .

            - name: Run Ruff
              run: ruff check --output-format=github .

            - name: Run Ruff Format
              run: ruff format --diff .

            - name: Run mypy
              run: |
                  mypy --install-types --non-interactive

            - name: Run pylint
              run: |
                  pylint artistools

    superlinter:
        name: Super linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  # Full git history is needed to get a proper list of changed files within `super-linter`
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Create .env
              run: |
                  touch .env

            - name: Lint Code Base
              uses: github/super-linter/slim@v4
              env:
                  LINTER_RULES_PATH: ./
                  FILTER_REGEX_EXCLUDE: .*/lightcurveplotly.js
                  # LOG_LEVEL: WARNING
                  PYTHON_BLACK_CONFIG_FILE: pyproject.toml
                  PYTHON_MYPY_CONFIG_FILE: pyproject.toml
                  VALIDATE_PYTHON_BLACK: false
                  VALIDATE_PYTHON_MYPY: false
                  VALUDATE_PYTHON_FLAKE8: false
                  VALIDATE_BASH: false
                  VALIDATE_CSS: false
                  VALIDATE_HTML: false # can't understand Django templates
                  VALIDATE_GITLEAKS: false
                  VALIDATE_JSCPD: false
                  VALIDATE_PYTHON_ISORT: false
                  YAML_ERROR_ON_WARNING: false
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
